#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/park/work/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/park/work/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/park/code/neuron/al_V2/x86_64/.libs/libnrnmech.so" "$@"
